// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkaxdnyriytsabhlowyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYXhkbnlyaXl0c2FiaGxvd3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzYwNDYsImV4cCI6MjA2Mzc1MjA0Nn0.BorMxR1gHjYGbjjuye82JVTdMmcLUtACV3JxHtUBKR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);